<!DOCTYPE html>
<html>
<title>tridiv.com</title>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-navbar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
<body>

<!-- Navbar -->
<ul class="w3-navbar w3-black w3-card-2 w3-top w3-left-align w3-large">
  <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
    <a class="w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
  </li>
  <li><a href="#" class="w3-padding-large w3-white">Home</a></li>
  <li class="w3-hide-small"><a href="#" class="w3-padding-large w3-hover-white">Link 1</a></li>
  <li class="w3-hide-small"><a href="#" class="w3-padding-large w3-hover-white">Link 2</a></li>
  <li class="w3-hide-small"><a href="#" class="w3-padding-large w3-hover-white">Link 3</a></li>
  <li class="w3-hide-small"><a href="#" class="w3-padding-large w3-hover-white">Link 4</a></li>
</ul>

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:51px">
  <ul class="w3-navbar w3-left-align w3-large w3-black">
    <li><a class="w3-padding-large" href="#">Link 1</a></li>
    <li><a class="w3-padding-large" href="#">Link 2</a></li>
    <li><a class="w3-padding-large" href="#">Link 3</a></li>
    <li><a class="w3-padding-large" href="#">Link 4</a></li>
  </ul>
</div>

<!-- Header -->
<div class="w3-container w3-red w3-center w3-padding-128">
  <h1 class="w3-margin w3-jumbo">START PAGE</h1>
  <p class="w3-xlarge">Template by w3.css</p>
  <button class="w3-btn w3-padding-16 w3-large w3-margin-top">Get Started</button>
</div>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h1>Cell Phone</h1>
    <iframe style='width:800px;height:600px' src='http://tridiv.com/app/index.html?dmlldz1mdWxsJmRvYz17InNldHRpbmdzIjp7Im5hbWUiOiJpUGhvbmUgNFMiLCJsaWdodCI6InN0YXRpYyIsInNoYWRlIjoiLjMiLCJ0aW50IjoiLjMiLCJib3JkZXIiOiIwIiwiYmciOiIjMDAwMDAwIiwiem9vbSI6IjEwMCIsIm1hdGNoIjoiMC41Iiwic25hcCI6Im9mZiJ9LCJzaGFwZXMiOlt7InR5cGUiOiJjdWJvaWQiLCJ5IjoiMS4xMjUiLCJ3IjoiMTYiLCJoIjoiLjUiLCJkIjoiMzIiLCJyeSI6IjE4MCIsImNyIjoiMi41IiwiY0FsbCI6IiMzMDMwMzAiLCJuYW1lIjpbImJhY2siXSwiaUJtIjoiaHR0cDovL3RyaWRpdi5jb20vZGVtb3MvaXBob25lNFMvYmFjay5wbmcifSx7InR5cGUiOiJjdWJvaWQiLCJ3IjoiMTYuNSIsImgiOiIxLjc1IiwiZCI6IjMyLjUiLCJjciI6IjIuNjI1IiwiY0FsbCI6IiNkNGQxY2YiLCJuYW1lIjpbIm1pZCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ5IjoiLTEuMSIsInciOiIxNiIsImgiOiIuNDUiLCJkIjoiMzIiLCJjciI6IjIuNSIsImNBbGwiOiIjMzAzMDMwIiwiaVRwIjoiaHR0cDovL3RyaWRpdi5jb20vZGVtb3MvaXBob25lNFMvdG9wLnBuZyIsIm5hbWUiOlsidG9wIl19LHsidHlwZSI6ImN1Ym9pZCIsIngiOiItOC4zOCIsInoiOi0xMi41LCJ3IjoiLjUiLCJoIjoiLjI1IiwiZCI6IjEuNSIsInJ4IjoiMCIsInJ6IjotOTAsImNyIjoiLjI1IiwiY0FsbCI6IiNjYmM4YzYiLCJuYW1lIjpbImxvY2siXX0seyJ0eXBlIjoiY3lsaW5kZXIiLCJ4IjoiLTguMzgiLCJ6IjoiLTkuNSIsImRpYW1ldGVyIjoiMS4yNSIsImgiOiIwLjI1IiwicnoiOi05MCwic2lkZXMiOiIxMiIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJidG4tcGx1cyJdfSx7InR5cGUiOiJjeWxpbmRlciIsIngiOiItOC4zOCIsInoiOiItNyIsImRpYW1ldGVyIjoiMS4yNSIsImgiOiIwLjI1IiwicnoiOi05MCwic2lkZXMiOiIxMiIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJidG4tbGVzcyJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4IjozLjUsInoiOiItMTYuMzgiLCJ3IjoiLjUiLCJoIjoiLjI1IiwiZCI6IjIuNzUiLCJyeCI6IjAiLCJyeSI6LTkwLCJyeiI6LTkwLCJjciI6Ii4yNSIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJwb3dlciJdfSx7InR5cGUiOiJjdWJvaWQiLCJ5IjoiLTEuMSIsInciOiIxNCIsImgiOiIuNCIsImQiOiIyMSIsImlUcCI6Imh0dHA6Ly90cmlkaXYuY29tL2RlbW9zL2lwaG9uZTRTL3NjcmVlbi5wbmciLCJuYW1lIjoiY3ViLTgifV19'></iframe>
     <h1>Video Games</h1>
    <iframe style='width:800px;height:600px' src='http://tridiv.com/app/index.html?dmlldz1mdWxsJmRvYz17InNldHRpbmdzIjp7Im5hbWUiOiJORVMiLCJsaWdodCI6InN0YXRpYyIsInNoYWRlIjoiLjQiLCJ0aW50IjoiLjE4IiwiYm9yZGVyIjoiMCIsImJnIjoiIzAwMDAwMCIsInpvb20iOiIxMDAiLCJzbmFwIjoib24iLCJtYXRjaCI6IjAuNSJ9LCJzaGFwZXMiOlt7InR5cGUiOiJjdWJvaWQiLCJ4IjotMTIuMjUsInkiOi0yLjI1LCJ3IjozLjUsImgiOjQuNSwiZCI6MjAsImNBbGwiOiIjRDNDQkM5IiwibmFtZSI6WyJ0b3AxIl19LHsidHlwZSI6ImN1Ym9pZCIsInkiOjAuNSwidyI6MjgsImgiOjEsImQiOjIwLCJjQWxsIjoiIzc0NkU3MiIsIm5hbWUiOlsibWlkQiJdfSx7InR5cGUiOiJwcmlzbSIsIngiOjEzLjI1LCJ5IjozLCJ3IjoyMCwiaCI6IjQiLCJkIjoiMS41IiwicngiOiItMTgwIiwicnkiOiI5MCIsImNBbGwiOiIjNzQ2RTcyIiwibmFtZSI6WyJhbmdsZVIiXX0seyJ0eXBlIjoicHJpc20iLCJ4IjotMTMuMjUsInkiOjMsInciOjIwLCJoIjoiNCIsImQiOiIxLjUiLCJyeCI6LTM2MCwicnkiOi05MCwicnoiOjE4MCwiY0FsbCI6IiM3NDZFNzIiLCJuYW1lIjpbImFuZ2xlTCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ5IjozLCJ3IjoyNSwiaCI6NCwiZCI6MjAsImNBbGwiOiIjNzQ2RTcyIiwibmFtZSI6WyJib3R0b20iXX0seyJ0eXBlIjoiY3Vib2lkIiwieCI6MTIuMjUsInkiOi0yLjI1LCJ3IjozLjUsImgiOjQuNSwiZCI6MjAsImNBbGwiOiIjRDNDQkM5IiwibmFtZSI6WyJ0b3AzIl19LHsidHlwZSI6ImN1Ym9pZCIsIngiOjguMjUsInkiOjAuMjUsInoiOiIxMC4wNSIsInciOjQuNSwiaCI6OS41LCJkIjoiMC4xIiwiY0FsbCI6IiMyMDIyMjEiLCJuYW1lIjpbImxpbmVGVCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4IjotMi4yNSwieSI6LTIuMjUsInoiOi0yLCJ3IjoxNi41LCJoIjo0LjUsImQiOjE2LCJjQWxsIjoiI0QzQ0JDOSIsIm5hbWUiOlsidG9wMiJdLCJjRnQiOiIjMWYxZjFmIn0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTIuMjUsInkiOi01LjUsInoiOjcuNzUsInciOjE2LjUsImgiOiIuNSIsImQiOiIzLjk1IiwicngiOjM1LjYsImNBbGwiOiIjRDNDQkM5IiwibmFtZSI6WyJkb29yVFAiXX0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTIuMjUsInkiOi0wLjUsInoiOjgsInciOjE2LjUsImgiOjEsImQiOjQsImNBbGwiOiIjRDNDQkM5IiwibmFtZSI6InRvcDExMTIxMyJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOi04LjI1LCJ5IjoyLjUsInoiOjEwLjI1LCJ3IjoyLjc1LCJoIjoxLCJkIjowLjUsImNBbGwiOiIjOGI4NDg4IiwibmFtZSI6WyJidG4xIl19LHsidHlwZSI6ImN1Ym9pZCIsIngiOi01LjI1LCJ5IjoyLjUsInoiOjEwLjI1LCJ3IjoiMi41IiwiaCI6IjEiLCJkIjoiLjUiLCJjQWxsIjoiIzhiODQ4OCIsIm5hbWUiOlsiYnRuMiJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4Ijo4LjI1LCJ5IjotMi4yNSwieiI6OCwidyI6NC41LCJoIjo0LjUsImQiOjQsImNBbGwiOiIjMjAyMjIxIiwibmFtZSI6WyJsaW5lRiJdLCJjUnQiOiIjZDNjYmM5In0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTIuMjUsInkiOi01LCJ6IjoxMC4yNSwidyI6MTYuNSwiaCI6MC41LCJkIjoiMy4yNSIsInJ4IjotNTMuOCwiY0FsbCI6IiNEM0NCQzkiLCJuYW1lIjpbImRvb3JGVCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4IjotMTAuMjUsInkiOjIuNSwieiI6IjEwLjA1IiwidyI6Ii41IiwiaCI6Ii41IiwiZCI6Ii4xIiwiY0FsbCI6IiNlZTRiNWQiLCJuYW1lIjpbImxpZ2h0Il19LHsidHlwZSI6ImN1Ym9pZCIsIngiOi01LCJ5IjotMi41LCJ6IjoxMC41LCJ3Ijo4LjI1LCJoIjoiMS44IiwiZCI6IjkiLCJjQWxsIjoiIzkwOTA5MCIsIm5hbWUiOlsiY2FydExUIl0sImNUcCI6IiM5MDkwOTAiLCJjRnQiOiIjOTA5MDkwIiwiaVRwIjoiaHR0cDovL3RyaWRpdi5jb20vZGVtb3MvbmVzL2NhcnQtdG9wLnBuZyIsImlGdCI6Imh0dHA6Ly90cmlkaXYuY29tL2RlbW9zL25lcy9jYXJ0LWZyb250LnBuZyJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOjMuNSwieSI6LTIuNSwieiI6MTAuNSwidyI6Mi4yNSwiaCI6IjEuOCIsImQiOiI5IiwiY0FsbCI6IiM5MDkwOTAiLCJuYW1lIjpbImNhcnRSVCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4IjowLjc1LCJ5IjotMi41LCJ6Ijo5LjI1LCJ3IjozLjI1LCJoIjoiMS44IiwiZCI6IjYuNSIsImNBbGwiOiIjOTA5MDkwIiwibmFtZSI6WyJjYXJ0TTIiXX0seyJ0eXBlIjoiY3Vib2lkIiwieCI6MC43NSwieSI6LTIuNSwieiI6MTMuNzUsInciOjMuMjUsImgiOiIwLjYiLCJkIjoiMi41IiwiY0FsbCI6IiM5MDkwOTAiLCJuYW1lIjpbImNhcnRNMSJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4Ijo4LjI1LCJ5IjotMi4yNSwieiI6LTgsInciOjQuNSwiaCI6NC41LCJkIjo0LCJjQWxsIjoiIzIwMjIyMSIsIm5hbWUiOlsibGluZUJLIl0sImNSdCI6IiNkM2NiYzkifSx7InR5cGUiOiJjdWJvaWQiLCJ4Ijo4LjI1LCJ5IjotMi4yNSwidyI6NC41LCJoIjo0LjUsImQiOjEyLCJjQWxsIjoiI2I4YjBhZSIsIm5hbWUiOlsibGluZU0iXX1dfQ=='></iframe>
    
    <h1>Space Ships</h1>
    <iframe style='width:800px;height:600px' src='http://tridiv.com/app/index.html?dmlldz1mdWxsJmRvYz17InNldHRpbmdzIjp7ImxpZ2h0Ijoic3RhdGljIiwiYm9yZGVyIjoiMSIsImJnIjoiIzAwMDAwMCIsInNoYWRlIjoiLjQiLCJ0aW50IjoiMC4xOCIsInpvb20iOiIxMDAiLCJtYXRjaCI6IjAuNSIsInNuYXAiOiJvbiIsIm5hbWUiOiJYLXdpbmcifSwic2hhcGVzIjpbeyJ0eXBlIjoiY3Vib2lkIiwieSI6IjAuNjI1IiwieiI6MS43NSwidyI6My41LCJoIjoiMy4yNSIsImQiOjcuNSwiY0FsbCI6IiNiZmM5YzUiLCJuYW1lIjoiY3ViLTEifSx7InR5cGUiOiJwcmlzbSIsInkiOi0xLjUsInoiOjMuMjUsInciOjMuNSwiaCI6Ii45IiwiZCI6IjQuNCIsIm8iOiIuNSIsImNBbGwiOiIjMzI4NGNlIiwiY0JrIjoiIzAyMTAxZiIsImNCbSI6IiMxMjNhNWYiLCJuYW1lIjoicHJpLTEifSx7InR5cGUiOiJjdWJvaWQiLCJ5IjotMS41LCJ6IjotMC41LCJ3IjozLjUsImgiOjEsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6ImN1Yi0yIn0seyJ0eXBlIjoicHJpc20iLCJ5IjoiLTAuNjI1IiwieiI6MTAuNSwidyI6MiwiaCI6Ii43NSIsImQiOjEwLCJjQWxsIjoiI2JmYzljNSIsIm5hbWUiOiJwcmktMiJ9LHsidHlwZSI6InByaXNtIiwieCI6MS4yNSwieSI6MC41LCJ6IjoxMC41LCJ3IjoxLjUsImgiOjEsImQiOjEwLCJyeiI6IjkwIiwiY0Z0IjoiIzhiMjYyNiIsImNMdCI6IiNiZmM5YzUiLCJjUnQiOiIjYmZjOWM1IiwibmFtZSI6InByaS0zIn0seyJ0eXBlIjoicHJpc20iLCJ4IjotMS4yNSwieSI6MC41LCJ6IjoxMC41LCJ3IjoxLjUsImgiOjEsImQiOjEwLCJyeiI6MjcwLCJjQWxsIjoiI2JmYzljNSIsImNGdCI6IiM4YjI2MjYiLCJuYW1lIjoicHJpLTQifSx7InR5cGUiOiJwcmlzbSIsInkiOi0wLjI1LCJ6IjoxNywidyI6IjIiLCJoIjoiMSIsImNBbGwiOiIjYjFiYmI3IiwibmFtZSI6InByaS01In0seyJ0eXBlIjoiY3Vib2lkIiwieSI6MC43NSwieiI6MTcsInciOjIsImgiOiIxIiwiY0FsbCI6IiNiMWJiYjciLCJuYW1lIjoiY3ViLTMifSx7InR5cGUiOiJjdWJvaWQiLCJ4IjotNy43NSwieSI6LTEuNzUsInoiOi01LjUsInciOiIxMSIsImgiOiIuNSIsImQiOiI0IiwicnoiOiIxNiIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6ImN1Yi00In0seyJ0eXBlIjoicHJpc20iLCJ4IjoyLjI1LCJ5IjotMC43NSwieiI6LTYuMjUsInciOjguNSwiaCI6IjIuNSIsImQiOjEsInJ5IjoiOTAiLCJjQWxsIjoiI2JmYzljNSIsImNMdCI6IiM2NzZmNzIiLCJuYW1lIjoicHJpLTYifSx7InR5cGUiOiJwcmlzbSIsIngiOi0yLjI1LCJ5IjotMC43NSwieiI6LTYuMjUsInciOjguNSwiaCI6IjIuNSIsImQiOjEsInJ5IjoiMjcwIiwicnoiOiIwIiwiY0FsbCI6IiNiZmM5YzUiLCJjUnQiOiIjNjc2ZjcyIiwibmFtZSI6InByaS03In0seyJ0eXBlIjoicHJpc20iLCJ4IjotMi4yNSwieSI6MS43NSwieiI6LTYuMjUsInciOjguNSwiaCI6IjIuNSIsImQiOjEsInJ4IjoiMTgwIiwicnkiOjI3MCwiY0FsbCI6IiNiZmM5YzUiLCJjTHQiOiIjNjc2ZjcyIiwibmFtZSI6InByaS04In0seyJ0eXBlIjoicHJpc20iLCJ4IjoyLjI1LCJ5IjoxLjc1LCJ6IjotNi4yNSwidyI6OC41LCJoIjoiMi41IiwiZCI6MSwicngiOiIxODAiLCJyeSI6IjkwIiwiY0FsbCI6IiNiZmM5YzUiLCJjUnQiOiIjNjc2ZjcyIiwibmFtZSI6InByaS05In0seyJ0eXBlIjoiY3lsaW5kZXIiLCJ4IjotMy41LCJ5IjotMiwieiI6LTUsImRpYW1ldGVyIjoiMi41IiwicngiOiItOTAiLCJzaWRlcyI6IjgiLCJjQWxsIjoiI2E2YWZhYyIsImNUcCI6IiMyZDMxMzMiLCJuYW1lIjoiY3lsLTEifSx7InR5cGUiOiJjeWxpbmRlciIsIngiOi0zLjUsInkiOi0yLCJ6IjotMTAsImRpYW1ldGVyIjoiMS41IiwicngiOiItOTAiLCJzaWRlcyI6IjYiLCJjQWxsIjoiIzdhNzE2YiIsIm5hbWUiOiJjeWwtMiJ9LHsidHlwZSI6InByaXNtIiwieCI6LTguNzUsInkiOi0yLCJ6IjotOC41LCJ3IjowLjUsImgiOiI5IiwiZCI6MiwicnkiOjE4MCwicnoiOiI3NCIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6InByaS0xMCJ9LHsidHlwZSI6ImN5bGluZGVyIiwieCI6LTEyLjI1LCJ5IjotNCwieiI6LTUuNSwiZGlhbWV0ZXIiOiIxLjUiLCJoIjoiNiIsInJ4IjoiLTkwIiwicnkiOiIxIiwic2lkZXMiOiI2IiwiY0FsbCI6IiM4Yjk1OWEiLCJjVHAiOiIjNGY0ZjRmIiwibmFtZSI6ImN5bC0zIn0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTEyLjI1LCJ5IjotNCwieiI6MiwidyI6IjAuNCIsImgiOiIwLjQiLCJkIjoiOSIsImNBbGwiOiIjYjFiYmI3IiwibmFtZSI6ImN1Yi01In0seyJ0eXBlIjoiY3Vib2lkIiwieCI6Ny43NSwieSI6LTEuNzUsInoiOi01LjUsInciOiIxMSIsImgiOiIuNSIsImQiOiI0IiwicngiOiItMTgwIiwicnoiOiIxNiIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6ImN1Yi02In0seyJ0eXBlIjoiY3lsaW5kZXIiLCJ4IjozLjUsInkiOi0yLCJ6IjotNSwiZGlhbWV0ZXIiOiIyLjUiLCJyeCI6Ii05MCIsInNpZGVzIjoiOCIsImNBbGwiOiIjYTZhZmFjIiwiY1RwIjoiIzJkMzEzMyIsIm5hbWUiOiJjeWwtNCJ9LHsidHlwZSI6ImN5bGluZGVyIiwieCI6My41LCJ5IjotMiwieiI6LTEwLCJkaWFtZXRlciI6IjEuNSIsInJ4IjoiLTkwIiwic2lkZXMiOiI2IiwiY0FsbCI6IiM3YTcxNmIiLCJuYW1lIjoiY3lsLTUifSx7InR5cGUiOiJjeWxpbmRlciIsIngiOjEyLjI1LCJ5IjotNCwieiI6LTUuNSwiZGlhbWV0ZXIiOiIxLjUiLCJoIjoiNiIsInJ4IjotOTAsInJ5IjoiLTEiLCJzaWRlcyI6IjYiLCJjQWxsIjoiIzhiOTU5YSIsImNUcCI6IiMzNTM1MzUiLCJuYW1lIjoiY3lsLTYifSx7InR5cGUiOiJjdWJvaWQiLCJ4IjoxMi4yNSwieSI6LTQsInoiOjIsInciOiIwLjQiLCJoIjoiMC40IiwiZCI6IjkiLCJjQWxsIjoiI2IxYmJiNyIsIm5hbWUiOiJjdWItNyJ9LHsidHlwZSI6InByaXNtIiwieCI6OC43NSwieSI6LTIsInoiOi04LjUsInciOjAuNSwiaCI6IjkiLCJkIjoyLCJyeCI6Ii0xODAiLCJyeiI6IjEwNiIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6InByaS0xMSJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOi03Ljc1LCJ5IjoyLjc1LCJ6IjotNS41LCJ3IjoiMTEiLCJoIjoiLjUiLCJkIjoiNCIsInJ6IjoiLTE2IiwiY0FsbCI6IiNiZmM5YzUiLCJuYW1lIjoiY3ViLTgifSx7InR5cGUiOiJjdWJvaWQiLCJ4Ijo3Ljc1LCJ5IjoyLjc1LCJ6IjotNS41LCJ3IjoiMTEiLCJoIjoiLjUiLCJkIjoiNCIsInJ4IjoiLTE4MCIsInJ6IjoiLTE2IiwiY0FsbCI6IiNiZmM5YzUiLCJuYW1lIjoiY3ViLTkifSx7InR5cGUiOiJjeWxpbmRlciIsIngiOi0zLjUsInkiOjMsInoiOi01LCJkaWFtZXRlciI6IjIuNSIsInJ4IjoiLTkwIiwic2lkZXMiOiI4IiwiY0FsbCI6IiNhNmFmYWMiLCJjVHAiOiIjMmQzMTMzIiwibmFtZSI6ImN5bC03In0seyJ0eXBlIjoiY3lsaW5kZXIiLCJ4IjotMy41LCJ5IjozLCJ6IjotMTAsImRpYW1ldGVyIjoiMS41IiwicngiOiItOTAiLCJzaWRlcyI6IjYiLCJjQWxsIjoiIzdhNzE2YiIsIm5hbWUiOiJjeWwtOCJ9LHsidHlwZSI6ImN5bGluZGVyIiwieCI6My41LCJ5IjozLCJ6IjotMTAsImRpYW1ldGVyIjoiMS41IiwicngiOiItOTAiLCJzaWRlcyI6IjYiLCJjQWxsIjoiIzdhNzE2YiIsIm5hbWUiOiJjeWwtOSJ9LHsidHlwZSI6ImN5bGluZGVyIiwieCI6My41LCJ5IjozLCJ6IjotNSwiZGlhbWV0ZXIiOiIyLjUiLCJyeCI6Ii05MCIsInNpZGVzIjoiOCIsImNBbGwiOiIjYTZhZmFjIiwiY1RwIjoiIzJkMzEzMyIsIm5hbWUiOiJjeWwtMTAifSx7InR5cGUiOiJwcmlzbSIsInkiOiIyLjYyNSIsInoiOi0wLjUsInciOiIzLjUiLCJoIjoiLjc1IiwicnoiOiItMTgwIiwiY0FsbCI6IiNiZmM5YzUiLCJuYW1lIjoicHJpLTEyIn0seyJ0eXBlIjoiY3Vib2lkIiwieSI6MC41LCJ6IjotNi4yNSwidyI6My41LCJkIjo4LjUsImNBbGwiOiIjYmZjOWM1IiwiY0JrIjoiIzY3NmY3MiIsIm5hbWUiOiJjdWItMTAifSx7InR5cGUiOiJjeWxpbmRlciIsIngiOjEyLjI1LCJ5Ijo1LCJ6IjotNS41LCJkaWFtZXRlciI6IjEuNSIsImgiOiI2IiwicngiOiItOTAiLCJyeSI6Ii0xIiwic2lkZXMiOiI2IiwiY0FsbCI6IiM4Yjk1OWEiLCJjVHAiOiIjNGY0ZjRmIiwibmFtZSI6ImN5bC0xMSJ9LHsidHlwZSI6ImN5bGluZGVyIiwieCI6LTEyLjI1LCJ5Ijo1LCJ6IjotNS41LCJkaWFtZXRlciI6IjEuNSIsImgiOiI2IiwicngiOiItOTAiLCJyeSI6Ii0xIiwic2lkZXMiOiI2IiwiY0FsbCI6IiM4Yjk1OWEiLCJjVHAiOiIjNGY0ZjRmIiwibmFtZSI6ImN5bC0xMiJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOi0xMi4yNSwieSI6NSwieiI6MiwidyI6IjAuNCIsImgiOiIwLjQiLCJkIjoiOSIsImNBbGwiOiIjYjFiYmI3IiwibmFtZSI6ImN1Yi0xMSJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOjEyLjI1LCJ5Ijo1LCJ6IjoyLCJ3IjoiMC40IiwiaCI6IjAuNCIsImQiOiI5IiwiY0FsbCI6IiNiMWJiYjciLCJuYW1lIjoiY3ViLTEyIn0seyJ0eXBlIjoicHJpc20iLCJ4Ijo4Ljc1LCJ5IjozLCJ6IjotOC41LCJ3IjowLjUsImgiOiI5IiwiZCI6MiwicngiOiItMTgwIiwicnoiOiI3NCIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6InByaS0xMyJ9LHsidHlwZSI6InByaXNtIiwieCI6LTguNzUsInkiOjMsInoiOi04LjUsInciOjAuNSwiaCI6IjkiLCJkIjoyLCJyeSI6MTgwLCJyeiI6IjEwNiIsImNBbGwiOiIjYmZjOWM1IiwibmFtZSI6InByaS0xNCJ9LHsidHlwZSI6InByaXNtIiwieCI6LTIuMDMxMDM0NDgyNzU4NjIwNiwieSI6MC41LCJ6IjoxLjc1LCJ3IjoiMS41IiwiaCI6MC41LCJkIjo3LjUsInJ6IjoyNzAsImNBbGwiOiIjYmZjOWM1IiwiY0Z0IjoiIzhiMjYyNiIsIm5hbWUiOiJwcmktMTUifSx7InR5cGUiOiJwcmlzbSIsIngiOjIuMDMxMDM0NDgyNzU4NjIwNiwieSI6MC40ODI3NTg2MjA2ODk2NTUxNCwieiI6MS43NSwidyI6IjEuNSIsImgiOjAuNSwiZCI6Ny41LCJyeiI6IjkwIiwiY0FsbCI6IiNiZmM5YzUiLCJjRnQiOiIjOGIyNjI2IiwibmFtZSI6InByaS0xNiJ9LHsidHlwZSI6InByaXNtIiwieSI6MS43NSwieiI6MTIsInciOiIyIiwiaCI6MSwiZCI6IjEzIiwicnoiOiItMTgwIiwiY0FsbCI6IiNiZmM5YzUiLCJuYW1lIjoicHJpLTE3In0seyJ0eXBlIjoiY3Vib2lkIiwieCI6My41LCJ5IjotMiwieiI6Ii0yLjQxIiwidyI6IjIuNSIsImgiOiIwLjI1IiwiZCI6IjAuMSIsInJ6IjoiLTE2IiwiY0FsbCI6IiM5Nzk3OWIiLCJuYW1lIjoiY3ViLTEzIn0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTMuNSwieSI6Ii0yIiwieiI6Ii0yLjQxIiwidyI6IjIuNSIsImgiOiIwLjI1IiwiZCI6IjAuMSIsInJ6IjoiMTYiLCJjQWxsIjoiIzk3OTc5YiIsIm5hbWUiOiJjdWItMTQifSx7InR5cGUiOiJjdWJvaWQiLCJ4IjotMy41LCJ5IjozLCJ6IjoiLTIuNDEiLCJ3IjoiMi41IiwiaCI6IjAuMjUiLCJkIjoiMC4xIiwicnoiOiItMTYiLCJjQWxsIjoiIzk3OTc5YiIsIm5hbWUiOiJjdWItMTUifSx7InR5cGUiOiJjdWJvaWQiLCJ4IjozLjUsInkiOjMsInoiOiItMi40MSIsInciOiIyLjUiLCJoIjoiMC4yNSIsImQiOiIwLjEiLCJyeiI6IjE2IiwiY0FsbCI6IiM5Nzk3OWIiLCJuYW1lIjoiY3ViLTE2In0seyJ0eXBlIjoiY3Vib2lkIiwieCI6LTguNSwieSI6Ii0yLjMiLCJ6IjotNS4yNSwidyI6IjIuNSIsImgiOiIuMSIsImQiOiIzLjUiLCJyeiI6IjE2IiwiY0FsbCI6IiNiZmM5YzUiLCJjVHAiOiIjOGIyNjI2IiwibmFtZSI6ImN1Yi0xNyJ9LHsidHlwZSI6ImN1Ym9pZCIsIngiOiI4LjUiLCJ5IjoiLTIuMyIsInoiOi01LjI1LCJ3IjoiMi41IiwiaCI6Ii4xIiwiZCI6IjMuNSIsInJ6IjoiLTE2IiwiY0FsbCI6IiNiZmM5YzUiLCJjVHAiOiIjOGIyNjI2IiwibmFtZSI6ImN1Yi0xOCJ9XX0='></iframe>
    </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    

    <div class="w3-twothird">
      <h1>Lorem Ipsum</h1>
      <h5 class="w3-padding-32">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>

      <p class="w3-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">
  <div class="w3-xlarge w3-padding-32">
   <a href="#" class="w3-hover-text-indigo"><i class="fa fa-facebook-official"></i></a>
   <a href="#" class="w3-hover-text-red"><i class="fa fa-pinterest-p"></i></a>
   <a href="#" class="w3-hover-text-light-blue"><i class="fa fa-twitter"></i></a>
   <a href="#" class="w3-hover-text-grey"><i class="fa fa-flickr"></i></a>
   <a href="#" class="w3-hover-text-indigo"><i class="fa fa-linkedin"></i></a>
 </div>
 <p>Powered by <a href="http://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

